<?php
/** @var \Leat\LoyaltyAdminUI\Block\Adminhtml\System\Config\FetchCreditNameButton $block */
?>
<div id="fetch_data_container">
    <input type="text"
           id="<?= $block->getData('element_id')?>"
           name="<?= $block->getData('element_name')?>"
           value="<?= $block->escapeHtml($block->getValue()) ?>"
           <?= $block->getData('html_attributes') ?>
    />
    <?= $block->getButtonHtml() ?>
</div>

<script>
    require(['jquery'], function($) {
        $('#fetch_data_button').click(function() {
            var scope = '<?= $block->getScope() ?>';
            var scopeId = '<?= $block->getScopeId() ?>';

            $.ajax({
                url: '<?= $block->escapeUrl($block->getAjaxUrl()) ?>',
                type: 'POST',
                dataType: 'json',
                data: {
                    scope: scope,
                    scope_id: scopeId
                },
                showLoader: true,
                success: function(response) {
                    if (response.success) {
                        $('#leat_credits_label').val(response.data);
                        $('input[name="groups[credits][fields][label][value]"]').val(response.data);
                    } else {
                        alert(response.message);
                    }
                },
                error: function() {
                    alert('An error occurred while fetching data.');
                }
            });
        });
    });
</script>
